### PR TITLE
adding a compound and interest calculator example

### PR DESCRIPTION
**Pull request by meg-1**
Adding a "compound and simple calculator" as a pyscript example.

### CODE REVIEW

**Comment by pauleveritt** [comment]
FYI, I have enough in my examples infrastructure to start working on PRs and I'm working on yours first. Thanks @meg-1 and sorry for the delay.

**Comment by pauleveritt** [comment]
First and simplest...is it ok if I make the `Calculate` button `disabled` while PyScript is loading up, so people won't try to fill it in too soon?

**Comment by meg-1** [comment]
> FYI, I have enough in my examples infrastructure to start working on PRs and I'm working on yours first. Thanks @meg-1 and sorry for the delay.

thank you very much for notifying! and no worries at all!

**Comment by meg-1** [comment]
> First and simplest...is it ok if I make the `Calculate` button `disabled` while PyScript is loading up, so people won't try to fill it in too soon?

absolutely it is! will keep that in mind for possible future examples

**Comment by pauleveritt** [comment]
It took a while, but we have finally added your example as the first external contribution in the Gallery.

**Pull request closed without merging**
