### PR TITLE
awesome-pyscript listing review

### PR DESCRIPTION
**Pull request by pauleveritt**
We still have more work to do: explain in the README how to contribute, link this into the main site, etc.

This PR starts a conversation about the entries, headings, and organization. If you have any listings that should be added, let's do so, as a way to chat and think.

### CODE REVIEW

**Comment by pauleveritt** [comment]
@jhanley-com Can you take a look at this and comment? It's a draft at the moment.

**Comment by marimeireles** [comment]
I'd like to recommend @jeffglass' and @do-me articles here :)

**Comment by marimeireles** [comment]
We should also add the discourse link here? Or is the README a better place?
Also post it broadly :)
On the anaconda forum for example + discord.
(I can post it on the forum)

**Comment by pauleveritt** [comment]
I think having an "Other" section for things that don't fit elsewhere would be a good place for the Discord link. I'll add it.

**Comment by JeffersGlass** [comment]
@pauleveritt All the posts are at [https://jeff.glass/tags/pyscript](https://jeff.glass/tags/pyscript), but I'm particularly proud of:

  * ['The 7 GUIs' in PyScript](https://jeff.glass/project/the-7-guis-pyscript/) project, and the [accompanying blog post](https://jeff.glass/post/7-guis-pyscript/) with explanations and details
  * [Image Uploading and Manipulation with PILLOW in PyScript](https://jeff.glass/post/pyscript-image-upload/)
  * [Pyscript/Pyodide and JS Object Passing](https://jeff.glass/post/pyscript-js-functions/), the core of which is [now a PyScript how-to](https://github.com/pyscript/pyscript/pull/753)
  * [Scikit Image Processing](https://jeff.glass/post/scikit-image-processing/) is more of a demo than an article, based on an idea from @kolibril13 - he's running much further with the idea over at  [kolibril13/pyscript-emoji-skimage](https://github.com/kolibril13/pyscript-emoji-skimage)

**Comment by pauleveritt** [comment]
Great, I just added your blog category as a "channel" in the file and added the emoji example under apps.

@JeffersGlass Wonder if you're interested in doing a review on what's being proposed for the Collective, or even joining as a co-show-runner?

**Comment by do-me** [comment]
> @JeffersGlass and @do-me can you give me a pointer to the articles?

Hi, sorry for the delay. I just added a category "pyscript" to my blog, see [here](https://geo.rocks/categories/pyscript/).
Thanks! More articles to come soon, I have some drafts ready.

**Comment by pauleveritt** [comment]
Very good, thanks @do-me I added the "channel" and pushed. Same offer to you: interested in reviewing or co-leading in this Collective stuff?

**Comment by do-me** [comment]
Hi @pauleveritt, thanks a lot for the invitation! I'd love to but I am quite limited in time this month. For the moment I'd like to focus on the pyscript documentation, particularly on file handling ([#595](https://github.com/pyscript/pyscript/issues/595)). As soon as I'm done with this, I gladly come back here!

**Comment by pauleveritt** [comment]
Sounds good, when you get a chance @do-me check back in.

**Comment by pauleveritt** [comment]
Wound up not getting any reviews so I went ahead and merged. We can improve as comments come in.

**Comment by marimeireles** [comment]
I reviewed it, sorry I wasn't clear about it.
And thank you for your work @pauleveritt!

**Pull request merged**
